### ISSUE TITLE
after-reboot with --limit is broken

### ISSUE THREAD

**Issue by millerdev** [dimagi/commcare-cloud#1564]
Running from softlayer control machine
```
dmiller@test1:~/.commcare-cloud/repo$ cchq softlayer after-reboot --limit=hqriak17 riakcs
This command will apply without running the check first. Continue? [y/N]y
ansible-playbook /home/dmiller/.commcare-cloud/repo/ansible/deploy_stack.yml -i /home/dmiller/.commcare-cloud/repo/environments/softlayer/inventory.ini -e @/home/dmiller/.commcare-cloud/repo/environments/softlayer/vault.yml -e @/home/dmiller/.commcare-cloud/repo/environments/softlayer/public.yml -e @/home/dmiller/.commcare-cloud/repo/environments/softlayer/.generated.yml --diff --limit 'hqriak17hqriak17:&riakcs' --tags after-reboot -u ansible --forks 15 --vault-password-file=/bin/cat
Vault Password:
 [WARNING]: Could not match supplied host pattern, ignoring: hqriak17hqriak17

ERROR! Specified hosts and/or --limit does not match any hosts
✗ Apply failed with status code 1
```
Note this in the full command: `--limit 'hqriak17hqriak17:&riakcs'`

**Comment by millerdev** [comment]
@dannyroberts ^

**Comment by millerdev** [comment]
no. I originally tried `cchq softlayer after-reboot --limit=hqriak17` and that failed with `after-reboot: error: too few arguments`, so I added `riakcs` to appease it. In hindsight, I think I should have just done `cchq softlayer after-reboot hqriak17`.

Incidentally, `cchq softlayer after-reboot --limit=riak17,riak16 riakcs` did work, but it only applied the command to `riak17` (not `riak16`). The syntax for running on multiple hosts is not intuitively clear to me, maybe I should have tried
`cchq softlayer after-reboot riak17,riak16` or `cchq softlayer after-reboot riak17 riak16`
?

**Comment by dannyroberts** [comment]
I think you want `cchq softlayer after-reboot hqriak17`

**Comment by dannyroberts** [comment]
and sorry, I should have been clearer in my last comment. Definitely a bug, so thanks for reporting. I've found the issue and will PR shortly

**Comment by millerdev** [comment]
Thanks for the quick response and fix!
