### ISSUE TITLE
Make git hook not match development/vault.yml or tests/*/vault.yml

### ISSUE THREAD

**Issue by pr33thi** [dimagi/commcare-cloud#1633]

**Comment by dannyroberts** [comment]
fixed here: https://github.com/dimagi/commcare-cloud/pull/1709/files#diff-6337eeb9e904b223332ed534a845b356R8

**Comment by dannyroberts** [comment]
That fixed a different related problem, but not the ones in the issue title

**Comment by pr33thi** [comment]
^Note: that makes sure that only filepaths ending in vault.yml get matched, still need to make it not match on development/ and tests/!

**Comment by pr33thi** [comment]
Fixed in these:
https://github.com/dimagi/commcare-cloud/pull/1762
https://github.com/dimagi/commcare-cloud/pull/1775
