### ISSUE TITLE
moving partitioning docs are out of date

### ISSUE THREAD

**Issue by emord** [dimagi/commcare-cloud#1776]
@dannyroberts I think you switched around how postgres definitions work and now https://github.com/dimagi/commcare-cloud/blob/je/more-services-in-ansible/docs/howto/move-partitioned-database.md#4-update-configuration is out of date (no rush on this, just ran across it and wanted to flag)

**Comment by dannyroberts** [comment]
Closed by https://github.com/dimagi/commcare-cloud/pull/1804
