### ISSUE TITLE
Add 'logs' action to service command

### ISSUE THREAD

**Issue by dannyroberts** [dimagi/commcare-cloud#2005]
It should just print out the location of the logs.

```
commcare-cloud <env> service elasticsearch logs
```

This will more or less just require hard-coding a mapping between services and log locations. A lot of the locations are documented at https://confluence.dimagi.com/display/commcarehq/Firefighting+HQ#FirefightingHQ-RestartingServices.

**Comment by dannyroberts** [comment]
@snopoke checking you're happy with the syntax. I chose it because it follows a familiar pattern so it'll flow better from our fingers than a separate command (`commcare-cloud <env> show-logs elasticsearch` or something), and it also emphasizes that the same set of services are available as are for the `commcare-cloud <env> service <service> start/stop/restart` commands.

**Comment by snopoke** [comment]
Looks fine to me. A lot of log locations are in the role vars too (though I haven't figured out how to load those into commands in a good way)

**Comment by pr33thi** [comment]
Completed here: https://github.com/dimagi/commcare-cloud/pull/2033
