### ISSUE TITLE
Have lower-touch way to permanently specify default user

### ISSUE THREAD

**Issue by dannyroberts** [dimagi/commcare-cloud#2410]
Would be nice to have an environment variable to check for what your ssh username.(`COMMCARE_CLOUD_DEFAULT_USERNAME`?)

This would then be used in `ssh` command by default, as well as other commands that infer the username for ssh or VPN.

**Comment by millerdev** [comment]
SSH already has a way to override usernames in its configuration, so it's not really a problem that needs to be solved for SSH. I have this in ~/.ssh/config:
```
Host *
    User dmiller
```
This is for places in commcare-cloud that use `getpass.getuser()` and provide no way to override that username.
