### ISSUE TITLE
How to start servers?

### ISSUE THREAD

**Issue by philipkaare** [dimagi/commcare-cloud#314]
Disclaimer: I know nothing about ansible, so this may very well be a stupid question - hope not :)

I have followed the instructions to set up the three vagrant machines and the control. It seems to have successfully deployed, but when I ssh into the machines no relevant processes seem to be running. Can anyone shed some light on what should be the next step in getting everything to run? 

Thanks!

**Comment by benrudolph** [comment]
Ok so this is pretty tough to answer without diving into a rabbit hole.

This repo is mainly used to configure our servers so they have all the right processes and software to run commcare hq. what you've done with the vagrant setup is essentially test that setup in VMs.

This is supposed to be run on actual machines, a cluster if you will; the instructions in the readme are bit misleading. you essentially need 4 things for this to work for you:

1. A control machine. Ansible needs to be on a machine for it to run and have access to the machines it's going to run commands on.

2. An inventory file. There's a sample one in this repo that will setup the services on the VMs. Our production inventory can be found [here](https://github.com/dimagi/commcare-hq/blob/master/fab/inventory/production). You can read more about them in the ansible [docs](http://docs.ansible.com/ansible/intro_inventory.html).

3. A vars file. There's a sample one in this repo called `dev.yml`. It has all the variables that configure HQ and have reasonable defaults. 

4. Once all the machines have the correct software, you'll need to deploy using our [fabric deploy system](https://github.com/dimagi/commcare-hq/blob/master/fab/fabfile.py) (`fab <your_env> deploy`). This will actually _start_ all the software and connect the services to the Django web server.

The process can be involved and the documentation is probably lacking at the moment. Apologies for the complexity but it's somewhat innate with having a complex application with lots of functionality that needs to work in different environments. Hope this helps a bit.

**Comment by philipkaare** [comment]
Hi @benrudolph thanks so much - I was a bit worried I was missing something obvious. I think I'll continue with setting everything up in docker, but this seems to be the best documentation of what dependencies are needed, so it's still a big help. Am I correct in understanding that fabric should then be run from the app1 server? I guess that's where it lives, right?

No need to apologize, I think it's wonderful what you are guys are contributing to the community with CommcareHQ. I might submit a pull request for some updated docs for the main repository - it's a bit misleading now as to how to get the system up and running - what do you think?

**Comment by czue** [comment]
> I might submit a pull request for some updated docs for the main repository - it's a bit misleading now as to how to get the system up and running - what do you think?

This would be great!

**Comment by benrudolph** [comment]
fabric would be run from your local machine to app1. it'd take some configuration to tell it to run on that VM. but if you're simply trying to run a local instance, use `./manage.py runserver` see [Running CommCareHQ](https://github.com/dimagi/commcare-hq#running-commcare-hq). ansible is for your production rig. +1 to the PR idea!

**Comment by philipkaare** [comment]
Right. the main reason I am interested is that there seems to be a lot of dependencies that ansible takes care of automatically, whereas setting everything up manually with docker, as I am trying do now, is a bit difficult. In any case I am trying to get close to a production rig. The internet connection in Bissau is not exactly stellar, so I am trying to get as much as possible in order from home.
